/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author lamit
 */
public class HomeManagement extends javax.swing.JFrame {

    /**
     * Creates new form HomeManagement
     */
    public HomeManagement() {
        initComponents();
    }
    public void setAction(ActionListener al1,ActionListener al2, ActionListener al3, ActionListener al4){
        btnHomeEdit.addActionListener(al1);
        btnHomeBook.addActionListener(al2);
        btnHomeCheckIn.addActionListener(al3);
        btnHomeCheckout.addActionListener(al4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHomeEdit = new javax.swing.JButton();
        btnHomeBook = new javax.swing.JButton();
        btnHomeCheckIn = new javax.swing.JButton();
        btnHomeCheckout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHomeEdit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnHomeEdit.setText("Chinh sua thong tin phong");

        btnHomeBook.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnHomeBook.setText("Dat phong");

        btnHomeCheckIn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnHomeCheckIn.setText("Checkin");

        btnHomeCheckout.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnHomeCheckout.setText("Tra phong va thanh toan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(btnHomeCheckIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnHomeEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(btnHomeBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btnHomeCheckout)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnHomeEdit)
                .addGap(55, 55, 55)
                .addComponent(btnHomeBook)
                .addGap(57, 57, 57)
                .addComponent(btnHomeCheckIn)
                .addGap(45, 45, 45)
                .addComponent(btnHomeCheckout)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomeBook;
    private javax.swing.JButton btnHomeCheckIn;
    private javax.swing.JButton btnHomeCheckout;
    private javax.swing.JButton btnHomeEdit;
    // End of variables declaration//GEN-END:variables
}
